### ISSUE TITLE
Tag v5.0 on Pakagist.org

### ISSUE THREAD

**Issue by patrickadvance** [laravel-notification-channels/webpush#100]
Pls tag v5.0 on pakagist, I am finding it hard to install this package in my laravel v6.0 app cause this version hasn't been tagged in pakagist.org

**Comment by cretueusebiu** [comment]
Unfortunately I don't have access to Packagist for this package. See #93

**Comment by patrickadvance** [comment]
@cretueusebiu Pls contact @themsaid to do this, cause many developers need it before they can upgrade their apps to Laravel v6.0 . Thanks

**Comment by danielcommesse** [comment]
I had to install it via repository in composer.json

`
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/laravel-notification-channels/webpush"
        }
    ],
`
then just do a composer update.

**Comment by acacha** [comment]
ping @themsaid

**Comment by JexPY** [comment]
@cretueusebiu  Hey, so how do you think should we wait or make "mirror" from branch?

**Comment by cretueusebiu** [comment]
You can also install it from git.
See https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/composer.json#L10

**Comment by JexPY** [comment]
@cretueusebiu Thanks for response.

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄
