### ISSUE TITLE
Undocumented breaking change - Content Encoding

### ISSUE THREAD

**Issue by mycarrysun** [laravel-notification-channels/webpush#101]
I am trying to upgrade to v5.0 so that I can use this package with Laravel 6.0.

Looks like there was a change with content encoding and you are sending it in client side [here](https://github.com/cretueusebiu/laravel-web-push-demo/blob/5c824cb485f6b347ec81ef4223be1ad7129dafe7/resources/js/components/NotificationsDemo.vue#L165).

Does this have to use the PushManager encodings? I'm not sure what is going on here. Are we able to just use UTF-8 if we know that is how the page is rendered from our server?

Also I had to create a migration to add the `content_encoding` column to the `push_subscriptions` table.

**Comment by atymic** [comment]
Feel free to PR the docs.
