### ISSUE TITLE
Laravel 6 Missing "subscribable_id"

### ISSUE THREAD

**Issue by BriBarthelemy** [laravel-notification-channels/webpush#102]
Hello,

I've installed webpush  5.0 and I got this error : "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'push_subscriptions.subscribable_id'"

It seems the column is not in the migration file.
Did I miss something?

Thank you

**Comment by cretueusebiu** [comment]
Do you have the `push_subscriptions` table already ?

`$table->morphs('subscribable');` should add `subscribable_type` and `subscribable_id`.

**Comment by poldixd** [comment]
Same here. I had a old migration:

```php
    public function up()
    {
        Schema::create('push_subscriptions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned()->index();
            $table->string('endpoint', 500);
            $table->string('public_key')->nullable();
            $table->string('auth_token')->nullable();
            $table->timestamps();

            $table->foreign('user_id')
                    ->references('id')
                    ->on('users')
                    ->onDelete('cascade');
        });
    }
```

**Comment by agitate** [comment]
This migration will update the old style table to the new one, with the morphs. Note that I've left the old user_id column in, and set it to nullable. This is so that you can test it out, and roll forwards and back, without loosing the data from that column, which is required when populating the new subscribable_id column. Might be of use. No guarantees, but it ran okay on my setup with thousands of entries in the table. No promises though. Backup first.

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class FixPushSubscriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        //$this->down();
        Schema::table('push_subscriptions', function (Blueprint $table) {
            /**
             * Have to add this as nullableMorphs when using it with existing
             * subscription data, and then update it after the update below
             */
            $table->nullableMorphs('subscribable');
            $table->string('content_encoding')->nullable();
            /**
             * Set this to nullable so that you can leave it in the table
             * enabling you to rollback the changes and not loose all the
             * user_ids
             */
            $table->unsignedBigInteger('user_id')->nullable()->change();
        });

        // Update the new morph columns with the old user_ids
        DB::update("update push_subscriptions set subscribable_type = 'App\\\\User', subscribable_id = user_id");

        Schema::table('push_subscriptions', function (Blueprint $table) {
            /**
             * Uncomment this line if you want to drop the old user_id column.
             * Note that you won't be able to roll back and forward without loosing
             * all of the existing user_ids if you do. Does no harm to leave it in.
             */
            // $table->dropForeign(['user_id']);
            
            /**
             *  Now that we've populated the new fields we can set the morph columns to not nullable.
             */ 
            $table->unsignedBigInteger('subscribable_id')->nullable(false)->change();
            $table->string('subscribable_type')->nullable(false)->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        /**
         * Copy the subscribable_id back to user_id for any new subscriptions
         * that you've added since the migration::up so that the up/down continues
         * to work without loosing the ids
         */
        DB::update("update push_subscriptions set user_id = subscribable_id");

        Schema::table('push_subscriptions', function (Blueprint $table) {
            $table->dropMorphs('subscribable');
            $table->dropColumn('content_encoding');
        });
    }
}

```

**Comment by vonec** [comment]
is this change merged?

**Comment by agitate** [comment]
It isn't really merge-able, as it is. I just needed a fix for my existing installation after the upgrade. Just create a new migration file:

`php artisan make:migration fix_push_subscriptions_table`

and then copy the code in to it from my post above and run the migration.

**Comment by aleex1848** [comment]
> It isn't really merge-able, as it is. I just needed a fix for my existing installation after the upgrade. Just create a new migration file:
> 
> `php artisan make:migration fix_push_subscriptions_table`
> 
> and then copy the code in to it from my post above and run the migration.

this gives me 
`SQLSTATE[HY000]: General error: 1832 Cannot change column 'user_id':  
   used in a foreign key constraint 'push_subscriptions_user_id_foreig  
  n' (SQL: ALTER TABLE push_subscriptions CHANGE user_id user_id BIGIN  
  T UNSIGNED DEFAULT NULL) `

**Comment by JuanRangel** [comment]
Thanks guys! I had the same issue as @aleex1848 but it is because my user table users int for the ID and not BigInt. I simply replaced this line
`$table->unsignedBigInteger('user_id')->nullable()->change();`
With
`$table->unsignedInteger('user_id')->nullable()->change();`
