### ISSUE TITLE
Web Push without gmp extension, possible?

### ISSUE THREAD

**Issue by sebsobseb** [laravel-notification-channels/webpush#104]
Hi,

The company where i host my website tells me they cannot install GMP on the webserver, thus I receive the following error:

> [WebPush] gmp extension is not loaded but is required for sending push notifications with payload or for VAPID authentication. You can fix this in your php.ini.

Is there a way to make Web Push work without GMP or do i have to host my site elsewhere? 🤔 

Thanks

**Comment by cretueusebiu** [comment]
The GMP extension is required by the https://github.com/web-push-libs/web-push-php dependency so it won't work without it.

**Comment by JoaoHamerski** [comment]
@cretueusebiu It's not required, its optional

> PHP 7.2+ and the following extensions:
gmp (optional but better for performance)
mbstring
curl
openssl

Its literally on the second line of Requirements.

How to disable the requirement of GMP?

**Comment by cretueusebiu** [comment]
I don't know about the readme, but the web-push-php lib will throw an error if you don't have it:
https://github.com/web-push-libs/web-push-php/blob/eddd95ca726bc529fbce7aaa90662584ad7ded3e/src/WebPush.php#L73

**Comment by staqd** [comment]
uncommenting "extension=gmp" in my php.ini, fixed it for me

plus if you subsequently run into a jwt-error ([Lcobucci\JWT\Parser] is not instantiable...), add "lcobucci/jwt": "3.3.3" in your composer.json and run composer update

**Comment by hacker-prime** [comment]
@staqd  I uncommented it but I still get the error. Are you aware of any possible reasons as to why that could be the case?

**Comment by hacker-prime** [comment]
@staqd It's a similar case for me.
