### ISSUE TITLE
No logs on Notification Send and didn't get the notification.

### ISSUE THREAD

**Issue by caiomcoliveira** [laravel-notification-channels/webpush#105]
Hello
I am trying to setup the push notification to my frontend in angular.

I already successfully subscribed to the push notifications, stored in the databased using angular's service worker.

I changed VAPID_SUBJECT to http://localhost:3000 ( I am serving on this port my angular frontend). 
However, when I send a new Notification I get nothing.  

Using npm's web-push works fine with the data stored on the push_notification table.

```php
<?php
namespace App\Notifications;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use NotificationChannels\WebPush\WebPushMessage;
use NotificationChannels\WebPush\WebPushChannel;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
class PushDemo extends Notification
{
    use Queueable;
    
    }
    
    public function via($notifiable)
    {
        return [WebPushChannel::class];
    }
    public function toWebPush($notifiable, $notification)
    {
        return (new WebPushMessage)
            ->title('TITLE')
            ->body('BODY')
    }
    
}
```

And on my NotificationController Push Route:

```php
<?php
public function push(){
    Notification::send(User::all(),new PushDemo);
    return "Success"
}
```

Also tried user->notify(new PushDemo); But still nothing. I get the success message and that is all. Nothing on the logs.

**Comment by caiomcoliveira** [comment]
Found the problem
The problem was that to notify users with the browser closed the json payload has to have a notification key.

{notification: {title: string, body: string } } .
So all I have to do is modify the toWebPush

**Comment by huynt57** [comment]
> Found the problem
> The problem was that to notify users with the browser closed the json payload has to have a notification key.
> 
> {notification: {title: string, body: string } } .
> So all I have to do is modify the toWebPush

Can you explain more how to add notification key to json payload in toWebPush ?. Thank you

**Comment by caiomcoliveira** [comment]
@huynt57 
WebPushChannel.php (I modified the source code to teste, however I will probably use Minishlink\WebPush\WebPush directly instead)

But you could modify line 50
```php
        $payload = json_encode($message->toArray());
```

to
```php
        $payload = json_encode(['notification' => $message->toArray()]);
```

**Comment by huynt57** [comment]
> @huynt57
> WebPushChannel.php (I modified the source code to teste, however I will probably use Minishlink\WebPush\WebPush directly instead)
> 
> But you could modify line 50
> 
> ```
>         $payload = json_encode($message->toArray());
> ```
> 
> to
> 
> ```
>         $payload = json_encode(['notification' => $message->toArray()]);
> ```

I will give it a try. Thank you !
