### ISSUE TITLE
$subscription->user is NULL

### ISSUE THREAD

**Issue by sebsobseb** [laravel-notification-channels/webpush#106]
I'm trying to get the user from a specific subscription.

```
public function dismiss(Request $request, $id)
    {
        if (empty($request->endpoint)) {
            return response()->json('Endpoint missing.', 403);
        }

        $subscription = PushSubscription::findByEndpoint($request->endpoint);
        if (is_null($subscription)) {
            return response()->json('Subscription not found.', 404);
        }

        return $subscription;
        ...
    }
```

The code above prints the subscription correctly:

```
{
    "id": 1,
    "subscribable_type": "App\\User",
    "subscribable_id": 7,
    "endpoint": "https://fcm.googleapis.com/fcm/send/...",
    "public_key": "XXX",
    "auth_token": "XXX",
    "content_encoding": "XXX",
    "created_at": "2019-10-23 23:10:55",
    "updated_at": "2019-10-23 23:10:55"
}
```
But, when i return `$subscription->user` it is `NULL`? 

Is this as expected?

FYI: Yes, the User model uses the `HasPushSubscriptions` trait.

**Comment by agorenja** [comment]
Hi, i wrote this message for migration for upgrading 3 -> 5
`public function up()
    {
        Schema::table('push_subscriptions', function (Blueprint $table) {
            $table->morphs('subscribable');
            $table->string('content_encoding')->after('auth_token')->nullable();
        });

        $subscriptions = PushSubscription::all();
        foreach ($subscriptions as $subscription) {
            try {
                /** @var \Modules\User\Entities\User $user */
                $user = User::find($subscription->user_id);
                $subscription->subscribable_type = get_class($user);
                $subscription->subscribable_id = $user->id;
                $subscription->save();
            } catch (\Exception $e) {
                echo 'ERROR: ' . $e->getMessage() . '   ' . $user->id;
            }
        }

        Schema::table('push_subscriptions', function (Blueprint $table) {
            $table->dropForeign(['user_id']);
            $table->dropColumn('user_id');
        });
    }
`

**Comment by leandrogrando** [comment]
@sebsobseb $subscription->subscribable return the user
