### ISSUE TITLE
Badge not working

### ISSUE THREAD

**Issue by Mirkin-source** [laravel-notification-channels/webpush#117]
It looks like the option badge isn't working.

```
    public function toWebPush($notifiable, $notification)
    {
        return (new WebPushMessage)
            ->title('Test')
            ->icon('/media/amulet-push.png')
            ->badge('/media/badge-128x128.png')
            ->body('Test')
            ->action('View app', 'action')
            ->data(['id' => $notification->id]);
    }
```

The push notification shows the chrome badge instead the defined badge

**Comment by climentjoan** [comment]
Hi Mirkin, how did you solve this? I'm unable to set icon nor badge.

Thanks

**Comment by climentjoan** [comment]
Hi there,

Did you solve this? Even if I set the badge parameter, it shows the image defined as "icon".

Thanks,
