### ISSUE TITLE
Is there any support for multiple subdomains?

### ISSUE THREAD

**Issue by kinjaldoyenhub** [laravel-notification-channels/webpush#120]
how can I use this library with multiple subdomains?

I want to send web push notifications with multiple origins (subdomains) that serve different content.

**Comment by lmatab** [comment]
Same here.

I am using this package to make my app tenant aware:

https://tenancyforlaravel.com/

Webpush works great for the main app although when subscribing it is not considering the tenants and it is saving the user notifications detail in the main db

**Comment by atymic** [comment]
You should be able to reconfigure on the fly.
If you'd like to PR code or docs feel free :)
