### ISSUE TITLE
Is it possible to throw exception or fire event upon failure?

### ISSUE THREAD

**Issue by carica** [laravel-notification-channels/webpush#121]
https://github.com/laravel-notification-channels/webpush/blob/5cb4009ea4b248616a61b3aa1313ea634adf1e21/src/ReportHandler.php#L23

When notifications were not sent due to network issues or mis configuration, we may inform the sender so that they could try again.
I think it is possible to throw exception or fire event upon failure and discard notification, instead of saving it to the database.

**Comment by cretueusebiu** [comment]
You can bind your custom report handler:

```php
use NotificationChannels\WebPush\WebPushChannel;
use NotificationChannels\WebPush\ReportHandlerInterface;

$this->app->when(WebPushChannel::class)
            ->needs(ReportHandlerInterface::class)
            ->give(MyCustomReportHandler::class);

class MyCustomReportHandler implements ReportHandlerInterface
{
    /**
     * Handle a message sent report.
     *
     * @param \Minishlink\WebPush\MessageSentReport $report
     * @param \NotificationChannels\WebPush\PushSubscription $subscription
     * @param \NotificationChannels\WebPush\WebPushMessage $message
     * @return void
     */
    public function handleReport($report, $subscription, $message)
    {
        if ($report->isSuccess()) {
            return;
        }

        // Add your custom logic...

        if ($report->isSubscriptionExpired()) {
            $subscription->delete();
        }
    }
}
```

**Comment by guestisp** [comment]
Same issue here.
When using Laravel `->notify()` method how can i be sure that at leat one endpoint has got the message properly ? If not, I have to use a fallback channel.
