### ISSUE TITLE
How to keep a log of the sent messages?

### ISSUE THREAD

**Issue by techguydev** [laravel-notification-channels/webpush#123]
Thanks for this package.

I would like to to know if there is a way to have a log of all the messages sent, so be in FCM or in our systems so we can keep track of the ones that a delivered correctly.

Thanks

**Comment by atymic** [comment]
https://laravel.com/docs/7.x/notifications#notification-events
Not sure if listening for the events is helpful? We may need to expose the reponses

**Comment by cretueusebiu** [comment]
Should be possible now with the new events.
