### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by voske** [laravel-notification-channels/webpush#126]
i still get the error:

 php artisan vendor:publish --provider="NotificationChannels\WebPush\WebPushServiceProvider" --tag="migrations"
Unable to locate publishable resources.
Publishing complete.

anyone know what is failing?

**Comment by MaoX17** [comment]
i have same error:
php artisan vendor:publish --provider="NotificationChannels\WebPush\WebPushServiceProvider" --tag="config"
Unable to locate publishable resources.
Publishing complete.


and 
Trait 'NotificationChannels\WebPush\HasPushSubscriptions' not found 

sorry i'm not an expert

**Comment by inonbaguio** [comment]
Was this ever fixed? I'm still getting this error
