### ISSUE TITLE
Memory size exhausted

### ISSUE THREAD

**Issue by pdellepiane** [laravel-notification-channels/webpush#131]
By executing the command `composer require laravel-notification-channels/webpush` I get the following error:

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 134217736 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 84

Any clue how to fix it?

Thanks in advance.

**Comment by atymic** [comment]
See: https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

Not an issue from this repo.
