### ISSUE TITLE
Unable To Install GMP Error

### ISSUE THREAD

**Issue by pratikmmt** [laravel-notification-channels/webpush#133]
Hi All,

I'm getting below given error while installing this package view Composer

`  Problem 1
    - laravel-notification-channels/webpush 5.0.0 requires minishlink/web-push ^5.0 -> satisfiable by minishlink/web-push[v5.0.0, v5.1.0, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5].
    - laravel-notification-channels/webpush 5.0.1 requires minishlink/web-push ^5.0 -> satisfiable by minishlink/web-push[v5.0.0, v5.1.0, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5].
    - laravel-notification-channels/webpush 5.0.2 requires minishlink/web-push ^5.0 -> satisfiable by minishlink/web-push[v5.0.0, v5.1.0, v5.2.0, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5].
    - minishlink/web-push v5.0.0 requires web-token/jwt-key-mgmt ^1.0 -> satisfiable by web-token/jwt-key-mgmt[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - minishlink/web-push v5.1.0 requires web-token/jwt-key-mgmt ^1.0 -> satisfiable by web-token/jwt-key-mgmt[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.0 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.1 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.10 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.2 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.3 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.4 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.5 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.6 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.7 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.8 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.9 requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.3.x-dev requires web-token/jwt-core ^1.3 -> satisfiable by web-token/jwt-core[v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.0 requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.1 requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.2 requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.3 requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.4 requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.2.x-dev requires web-token/jwt-core ^1.2 -> satisfiable by web-token/jwt-core[v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.0 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.0-beta1 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.0-beta2 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.0-beta3 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.0-beta4 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.1 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.2 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.3 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.4 requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.1.x-dev requires web-token/jwt-core ^1.1 -> satisfiable by web-token/jwt-core[v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.0 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.1 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.2 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.3 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.4 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.5 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.6 requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-key-mgmt v1.0.x-dev requires web-token/jwt-core ^1.0 -> satisfiable by web-token/jwt-core[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.x-dev, v1.1.0, v1.1.0-beta1, v1.1.0-beta2, v1.1.0-beta3, v1.1.0-beta4, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.x-dev, v1.3.0, v1.3.1, v1.3.10, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.3.8, v1.3.9, v1.3.x-dev].
    - web-token/jwt-core v1.3.x-dev requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.9 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.8 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.7 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.6 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.5 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.10 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.3.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.x-dev requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.2.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.x-dev requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.0-beta4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.0-beta3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.0-beta2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.0-beta1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.1.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.x-dev requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.6 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.5 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - web-token/jwt-core v1.0.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.5 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.4 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.3 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - minishlink/web-push v5.2.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - Installation request for laravel-notification-channels/webpush ^5.0 -> satisfiable by laravel-notification-channels/webpush[5.0.0, 5.0.1, 5.0.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /opt/cpanel/ea-php72/root/etc/php.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-bcmath.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-calendar.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-ctype.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-curl.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-dom.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-fileinfo.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-ftp.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-gd.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-iconv.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-imap.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-json.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-mbstring.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-mysqlnd.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-pdo.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-phar.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-posix.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-simplexml.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-sockets.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-sqlite3.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-tokenizer.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xml.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xmlwriter.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-xsl.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/20-zip.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-mysqli.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-pdo_mysql.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-pdo_sqlite.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-wddx.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/30-xmlreader.ini
    - /opt/cpanel/ea-php72/root/etc/php.d/zzzzzzz-pecl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`

**Comment by cretueusebiu** [comment]
You need to install the ext-gmp PHP extension.
