### ISSUE TITLE
In ECKey.php line 148:    Unable to create the key  -> php artisan webpush:vapid

### ISSUE THREAD

**Issue by metalsadman** [laravel-notification-channels/webpush#136]
getting error:
```bash
$ php artisan webpush:vapid

   RuntimeException  : Unable to create the key

  at E:\laravel-webpush\vendor\web-token\jwt-core\Util\ECKey.php:148 
    144|             'curve_name' => self::getOpensslCurveName($curve),
    145|             'private_key_type' => OPENSSL_KEYTYPE_EC,
    146|         ]);
    147|         if (false === $key) {
  > 148|             throw new RuntimeException('Unable to create the key');
    149|         }
    150|         $result = openssl_pkey_export($key, $out);
    151|         if (false === $result) {
    152|             throw new RuntimeException('Unable to create the key');

  Exception trace:

  1   Jose\Component\Core\Util\ECKey::createECKeyUsingOpenSSL("P-256")
      E:\laravel-webpush\vendor\web-token\jwt-core\Util\ECKey.php:110
  2   Jose\Component\Core\Util\ECKey::createECKey("P-256", [])
      E:\laravel-webpush\vendor\web-token\jwt-key-mgmt\JWKFactory.php:75
```

when running `php artisan webpush:vapid`.

Laravel Framework 6.18.0

**Comment by elsayed85** [comment]
do you solve it ?

**Comment by metalsadman** [comment]
> do you solve it ?

Nope

**Comment by Juancml1913** [comment]
Hello,

I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"

hope it helps you

**Comment by metalsadman** [comment]
> Hello,
> 
> I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"
> 
> hope it helps you

thanks it works, just going to leave this open, as this seem to be a bug in the current version.

**Comment by utechs** [comment]
> Hello,
> 
> I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"
> 
> hope it helps you

composer update threw an error 
- web-token/jwt-core v1.3.x-dev requires ext-gmp * -> the requested PHP extension gmp is missing from your system.

**Comment by cretueusebiu** [comment]
You need to have openssl configured.
https://www.php.net/manual/en/openssl.installation.php

**Comment by kirschkern** [comment]
>     * the requested PHP extension gmp is missing from your system

I solved it by enabling the gmp extension in my php.ini.
Open your php.ini and search for extension=gmp. Remove the ";" in front of the line.

**Comment by MrEduar** [comment]
> > ```
> > * the requested PHP extension gmp is missing from your system
> > ```
> 
> I solved it by enabling the gmp extension in my php.ini.
> Open your php.ini and search for extension=gmp. Remove the ";" in front of the line.

Not work for me
