### ISSUE TITLE
Can not create the vapid key

### ISSUE THREAD

**Issue by HuyNguyen206** [laravel-notification-channels/webpush#138]
When I run this command "php artisan webpush:vapid" 
It shows this error below
![image](https://user-images.githubusercontent.com/30259638/94988013-6acc3a80-0594-11eb-879d-232ae150eecf.png)
Can someone help me to solve it?

I use Laravel 7.0

Thanks in advance

**Comment by Juancml1913** [comment]
Hello,

I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"

hope it helps you

**Comment by HuyNguyen206** [comment]
Thank @Juancml1913

**Comment by jrchan30** [comment]
@HuyNguyen206 another way is to use a vapid keys online generator, then manually add generated public and private keys to your env file. Not sure if this method is good, but hey it works for my small project.

Hope this helps you and other people who face this problem.

**Comment by jacobdennisp** [comment]
I had a similar issue which kept showing " Unable to create the key", So, I installed Open SSL and it worked like a charm!

**Comment by eissaweb** [comment]
Downgraded the package from ^7 to 5.2.5 and it worked, you need gmp extension though

**Comment by ERaufi** [comment]
i am facing same problem i use laragon and laravel 11
