### ISSUE TITLE
Unable to generate VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY in Laravel

### ISSUE THREAD

**Issue by Nana-asiamah98** [laravel-notification-channels/webpush#139]
I've tried generating a VAPID key for my Laravel Project. I'm done entering `php artisan webpush:vapid` in the CLI and I get this error _RuntimeException Unable to create the key._ Is there anyway to resolve this error?

**Comment by Juancml1913** [comment]
Hello,

I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"

hope it helps you

**Comment by Nana-asiamah98** [comment]
Thank you very much

**Comment by zmeulDev** [comment]
I spent good hours looking for this answer. Thanks.

**Comment by MrEduar** [comment]
> Hello,
> 
> I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"
> 
> hope it helps you

This does not work for the latest version of Laravel 8, as they are not compatible.

**Comment by jadamec** [comment]
> Hello,
> 
> I solved it by typing "5.0.2" in "laravel-notification-channels/webpush" in the composer.json file, don't forget to run the command "composer update"
> 
> hope it helps you

This also doesn't work for the PHP 8, as they are not compaatible...
