### ISSUE TITLE
How to turn off warning messages

### ISSUE THREAD

**Issue by sebsobseb** [laravel-notification-channels/webpush#146]
Thanks for this package.

Since we're sending out quite a lot of push notifications to our users, our logs are being "polluted" by these warning messages:

**Example [410 Gone]**
```Notification failed to sent for subscription https://fcm.googleapis.com/fcm/send/eW6SoaUtZLE:APA91bF8K202_2v9rXVtyOFY0wwIzGgYQWHFKLLOnM4Fv20u4d9jLB5j8SpaOeyNJZmvB4GWLvgHEOGmeRsW2_Z4hJRSxeujmAaBwuwXQDLOn9N03K4GUwRbGsMCn2uNMiWDIpOJE5p9: Client error: `POST https://fcm.googleapis.com/fcm/send/eW6SoaUtZLE:APA91bF8K202_2v9rXVtyOFY0wwIzGgYQWHFKLLOnM4Fv20u4d9jLB5j8SpaOeyNJZmvB4GWLvgHEOGmeRsW2_Z4hJRSxeujmAaBwuwXQDLOn9N03K4GUwRbGsMCn2uNMiWDIpOJE5p9` resulted in a `410 Gone` response:``` push subscription has unsubscribed or expired.

Questions
1. Is there a way to turn those warnings off?
2. Are those warnings actually solvable or should I just ignore them?

**Comment by KieronHolmes** [comment]
1 - It doesn't appear there is currently a way to turn these notifications off, as ReportHandler.php includes the following code, which is always executred if the push notification was not successful.

```
Log::warning("Notification failed to sent for subscription {$subscription->endpoint}: {$report->getReason()}");
```
I'll create a PR later today including the ability to toggle this log on/off from the configuration file.

2 - I believe these don't need to be actioned, as the code checks to see if the subscription is expired if it fails to send a notification, and subsequently deletes the subscription from the Laravel database.

```
if ($report->isSubscriptionExpired()) {
    $subscription->delete();
}
```

**Comment by cretueusebiu** [comment]
Warning message has been removed and 2 events were added.
https://github.com/laravel-notification-channels/webpush/releases/tag/5.1.0
