### ISSUE TITLE
Unable to send push notifications

### ISSUE THREAD

**Issue by jeankhawand** [laravel-notification-channels/webpush#149]
local.WARNING: Notification failed to sent for subscription https://fcm.googleapis.com/fcm/send/*: Client error: POST https://fcm.googleapis.com/fcm/send/* resulted in a 403 Forbidden response:
the key in the authorization header does not correspond to the sender ID used to subscribe this user. Please ensure you (truncated...)
Any idea ?

**Comment by jeankhawand** [comment]
I was able to send push notifications locally but when I did deploy the app on a vps I am facing this issue. I tried also to use same keys used locally to test it on vps with no luck !

**Comment by viaativaweb** [comment]
I just had the same issue...

**Comment by viaativaweb** [comment]
it was caused by pushManager.subscribe using a different `VAPID_PUBLIC_KEY `than the one in the .env file
