### ISSUE TITLE
Call to a member function isEmpty() null

### ISSUE THREAD

**Issue by Rakesh2907** [laravel-notification-channels/webpush#154]
Hello,

When set  Notification::send(User::all(),new PushDemo); in my controller getting following error

Call to a member function isEmpty() on null at D:\\xampp\\htdocs\\XXXXXX\\vendor\\laravel-notification-channels\\webpush\\src\\WebPushChannel.php:44)

Please help me.

**Comment by kirkbushell** [comment]
I'm curious how to do this when your subscribers don't have user models. Ie. They've subscribed via the browser notice, but don't have a user account.
