### ISSUE TITLE
Invalid data: only uncompressed keys are supported.

### ISSUE THREAD

**Issue by mreduar** [laravel-notification-channels/webpush#155]
Hi, I am trying to send a push notification and when the notification is being sent I get this error.
![image](https://user-images.githubusercontent.com/22550119/113446732-73c48a00-93c6-11eb-8b7e-cb466229ad95.png)

To make the subscription I am using several js methods.
You can see those methods [here](https://github.com/SagarMaheshwary/webpush-example/blob/master/public/js/enable-push.js).
I have used another method to generate the key because when I run the `php artisan webpush:vapid` command I get an error `Unable to create the key` So I downloaded the [web-push](https://www.npmjs.com/package/web-push) package and generated the key with it.

Any suggestions?

**Comment by martijnimhoff** [comment]
I also had this issue. My mistake was that I put the auth and p256dh the wrong way around.

After swapping those variables, it worked!
