### ISSUE TITLE
Generating the VAPID keys throws an error 'Unable to create the key'

### ISSUE THREAD

**Issue by jadamec** [laravel-notification-channels/webpush#157]
Generating the VAPID keys throws an error **Unable to create the key**.

`php artisan webpush:vapid`

Any suggestions or fixes, please?
![Screenshot_1](https://user-images.githubusercontent.com/19595874/114852709-4ecb1080-9de3-11eb-84da-1165fcd75f72.jpg)

**Comment by cretueusebiu** [comment]
It all comes down from the openssl configuration.
https://www.php.net/manual/en/function.openssl-pkey-export.php

**Comment by jadamec** [comment]
Thanks, but how to test this on the localhost using XAMPP, please?

**Comment by jadamec** [comment]
I found the solution! These issues really relates on the specific config.

FIX: https://stackoverflow.com/questions/17272809/openssl-pkey-export-and-cannot-get-key-from-parameter-1/18869750#18869750
