### ISSUE TITLE
install using composer 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [laravel-notification-channels/webpush#16]
I tried to install your package by composer by I got this error: 

`Problem 1
    - mdanter/ecc v0.4.2 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - mdanter/ecc v0.4.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - mdanter/ecc v0.4.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - laravel-notification-channels/webpush 0.1.1 requires minishlink/web-push 1.1.* -> satisfiable by minishlink/web-push[v1.1].
    - minishlink/web-push v1.1 requires mdanter/ecc ^0.4.0 -> satisfiable by mdanter/ecc[v0.4.0, v0.4.1, v0.4.2].
    - Installation request for laravel-notification-channels/webpush ^0.1.1 -> satisfiable by laravel-notification-channels/webpush[0.1.1].`

**Comment by cretueusebiu** [comment]
You have to enable the [gmp](http://php.net/manual/en/book.gmp.php) PHP extension.

**Comment by AbdulazizAlmohsen** [comment]
tried 
`sudo apt-get install libgmp-dev
sudo apt-get install php5-gmp
sudo service apache2 reload` 

but I still face this issue

**Comment by cretueusebiu** [comment]
Now it looks like you don't have the the [OpenSSL](http://php.net/manual/en/book.openssl.php) PHP extension installed.

**Comment by AbdulazizAlmohsen** [comment]
I'm using brew to install OpenSSL but I couldn't link it. 
`Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version`

Then I try to force link: 

`Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib` 

I dont get what this means! I know this is not an issue from your package but could you please help:)

**Comment by cretueusebiu** [comment]
I'm using Windows and Linux so I don't know how to install it on a Mac.

**Comment by AbdulazizAlmohsen** [comment]
thank you.
