### ISSUE TITLE
Move composer requirement from Laravel 5.3 to 5.3 or 5.4?

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#17]
Is there a way to also allow this module to be used in the recently released laravel 5.4?

`Problem 1
    - Installation request for laravel-notification-channels/webpush ^0.1.1 -> satisfiable by laravel-notification-channels/webpush[0.1.1].
    - Conclusion: remove laravel/framework v5.4.3
    - Conclusion: don't install laravel/framework v5.4.3`

**Comment by cretueusebiu** [comment]
It will be updated today to support Laravel 5.4.

**Comment by iamgoodbytes** [comment]
Fantastic, can't wait to give it a spin

**Comment by cretueusebiu** [comment]
Both the package and the [demo](https://github.com/cretueusebiu/laravel-web-push-demo) have been updated to Laravel 5.4.
