### ISSUE TITLE
\Safe\Resource error when installing package

### ISSUE THREAD

**Issue by dkvhin** [laravel-notification-channels/webpush#177]
PHP : 8.1
Laravel 9

When installing, I'm getting the followig warning and error

`PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\Safe\resource" or import the class with "use" to suppress this warning in D:\xampp\htdocs\rland\vendor\thecodingmachine\safe\generated\sockets.php`

`integer" will be interpreted as a class name. Did you mean "int"? Write "\Safe\integer" or import the 
class with "use" to suppress this warning`

**Comment by githesix** [comment]
This package requires:
`minishlink/web-push ^7.0`
that requires:
`web-token/jwt-util-ecc ^2.0|^3.0.2`
that requires:
`thecodingmachine/safe ^0.1.14`
that's getting too old to work with PHP8.1

Installing the latest version of [web-token/jwt-util-ecc](https://github.com/web-token/jwt-util-ecc) updates [thecodingmachine/safe](https://github.com/thecodingmachine/safe) and solves the warning

**Comment by pablomadariaga** [comment]
I have the same problem i am using laravel v9.24.0 and php 8.1.9

![image](https://user-images.githubusercontent.com/69119357/184185460-702d0d58-784d-48fd-bc1d-57a0ea247184.png)

**Comment by adeiming** [comment]
same here

**Comment by dkvhin** [comment]
> This package requires: `minishlink/web-push ^7.0` that requires: `web-token/jwt-util-ecc ^2.0|^3.0.2` that requires: `thecodingmachine/safe ^0.1.14` that's getting too old to work with PHP8.1
> 
> Installing the latest version of [web-token/jwt-util-ecc](https://github.com/web-token/jwt-util-ecc) updates [thecodingmachine/safe](https://github.com/thecodingmachine/safe) and solves the warning

Worked.

Thank You :)

**Comment by pablomadariaga** [comment]
How can I perform this update?

**Comment by dkvhin** [comment]
> @dkvhin How can I perform this update?

Just execute

`composer require web-token/jwt-util-ecc`

This will install the latest package with the updated dependencies

**Comment by pablomadariaga** [comment]
> > @dkvhin¿Cómo puedo realizar esta actualización?
> 
> solo ejecuta
> 
> `composer require web-token/jwt-util-ecc`
> 
> Esto instalará el paquete más reciente con las dependencias actualizadas

thank you very much it worked

**Comment by Mir-37** [comment]
I am still stuck on this! My php version is 8.0.28 and composer won't even let me force update "web-token/jwt-utill-ecc", any solution?
