### ISSUE TITLE
GCM vs VAPID

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#18]
Hi! I was wondering if GCM keys are a requirement? I found this Laravel library through https://github.com/web-push-libs/web-push-php where GCM is obsolete and not required. Having used the web-push-php library successfully with VAPID, I was wondering if GCM is still used here (also now that google is suggesting to drop GCM for FCM/firebase). Thanks for you input!

**Comment by cretueusebiu** [comment]
For now you need GCM but I will try to migrate to VAPID soon.

**Comment by iamgoodbytes** [comment]
Thanks again @cretueusebiu - I'm still reading up on all things web push related and the use of GCM was confusing to me. It's starting to make more sense!

**Comment by iamgoodbytes** [comment]
When VAPID will be integrated for newer versions of Chrome and for Firefox, will GCM still be in the extension in order to support older version or chrome or will it be better to drop GCM completely and move your code to VAPID?

**Comment by cretueusebiu** [comment]
I guess move to VAPID. But I can't even find what versions of Chrome/Firefox support VAPID.

**Comment by iamgoodbytes** [comment]
Yeah it's a bit of a mess. Some useful info that I can find is the following:

https://developers.google.com/web/updates/2016/07/web-push-interop-wins
https://www.chromestatus.com/features/5748876422152192
"If you implement VAPID it'll work in all browsers that support web push" http://caniuse.com/#feat=push-api

**Comment by iamgoodbytes** [comment]
@cretueusebiu do you think there will be lots of breaking changes necessary once you move to VAPID? Or would you say it's rather safe to implement the module right now and upgrade in the future? Thanks for the feedback and the work on the module, it helps a lot in understanding how web push works.
