### ISSUE TITLE
403 Forbiden on Apple Safari

### ISSUE THREAD

**Issue by imrodrigoalves** [laravel-notification-channels/webpush#181]
Hello,
I've been testing implementing this package in a project that implements an SPA and API.
It works well until we test on Safari.

The error I receive:
**POST https://web.push.apple.com/IDENTIFIER` resulted in a `403 Forbidden` response: {\"reason\":\"BadJwtToken\"}** 

I've researched into the reasons Apple provide for such [here](https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_safari_and_other_browsers), yet I am not able to find a reason for it not to work :/

```
// env keys
VAPID_SUBJECT='http://localhost:8080' # Frontend URL for testing Service workers
VAPID_PUBLIC_KEY="MY-PUBLIC-KEY"
VAPID_PRIVATE_KEY="MY-PRIVATE-KEY"
```

According to a comment with the underlying library it should work without any changes. [Read here](https://github.com/web-push-libs/web-push-php/issues/347#issuecomment-1173667925).

Is someone able to help out?

Regards,
Rodrigo

**Comment by tobias992** [comment]
We have the same problem and are also looking for a solution.

**Comment by imrodrigoalves** [comment]
@tobias992 Any luck?

**Comment by peteruu** [comment]
i had a problem with this 
before
'subject' => 'admin@example.com'
after
'subject' => 'mailto: admin@example.com'

and also with this 
before
'topic' => 'new_event', // not defined by default,
after
'topic' => 'newEvent', // not defined by default,

I know that topic is not required but anyway.

**Comment by tobias992** [comment]
Our problem also was the 'subject' - after change to domain all was working fine.

**Comment by imrodrigoalves** [comment]
> Our problem also was the 'subject' - after change to domain all was working fine.

Can you elaborate on the change that was necessary on your side?

**Comment by imrodrigoalves** [comment]
Apparently locally it doesn't work. Needs to be a domain with `https`

**Comment by duswie** [comment]
Add an env var like VAPID_SUBJECT=mailto:xxx@example.de
