### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by paceband** [laravel-notification-channels/webpush#186]

**Comment by jonathanpmartins** [comment]
The pull request was created 2 weeks ago: https://github.com/laravel-notification-channels/webpush/pull/185

**Comment by modemb** [comment]
yes not working

**Comment by punyflash** [comment]
Waiting only for this package to update to migrate my project to Laravel 10... Please accept #185... T-T

**Comment by jonathanpmartins** [comment]
> Waiting only for this package to update to migrate my project to Laravel 10... Please accept #185... T-T

There is quick-fix here if you want to upgrade your project now. https://github.com/laravel-notification-channels/webpush/pull/185#issuecomment-1409422252
