### ISSUE TITLE
migrations not being generated

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#21]
First of all, thanks so much for taking the effort to upgrade to VAPID!

I'm currently trying out the new release, but noticed that there are not migrations being generated.
```
vagrant@server:~/Code/$ php artisan vendor:publish --provider="NotificationChannels\WebPush\WebPushServiceProvider" --tag="migrations"
Publishing complete.
vagrant@server:~/Code/$ php artisan migrate
Nothing to migrate.
```
Is that something I'm missing? I'm sure there are some default tables or columns you're generating normally?

Thanks again!

**Comment by cretueusebiu** [comment]
Can you check your `database/migrations` folder, is there a create_push_subscriptions_table migration there ?

**Comment by iamgoodbytes** [comment]
That's it. I had created a custom table myself before using your library and it has the exact same name.
