### ISSUE TITLE
Question: How to segment push messages

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#22]
Hi @cretueusebiu !

First of all, nice work on the vapid-update. I've implemented your library and it works great.
Right now, I'm trying to segment the push subscriptions, so that I can send only to some of them, not all of them.

Right now, when using the laravel notification, the push messages are sent to all subscriptions for a user. What I'm trying to do is keep track of subscriptions with a tag like "segment1", "segment2" and only target those subscriptions.

What would be a good way to approach this? My current approach would be to extend/overwrite your send function in WebPushChannel.php. 

I know this isn't an issue with the library, so if you don't have time to reply to this question I understand completely!

**Comment by iamgoodbytes** [comment]
Great idea, thanks for the input !

**Comment by iamgoodbytes** [comment]
@cretueusebiu do you have any experience with running this in queues with laravel? Seems like whenever I schedule sending the notifications via queues, the static::$segment is null, even when it's set correctly. Any idea how to work around that?

**Comment by cretueusebiu** [comment]
Maybe store the segments somewhere. Or try to somehow serialize the
segments on the model.
