### ISSUE TITLE
Send additional data / payload

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#23]
Is it possible to send additional data with the push message, besides the following five attributes?

```
return WebPushMessage::create()
            // ->id($notification->id)
            ->title( $this->notification_data['push_title'] )
            ->icon( $this->notification_data['push_icon'] )
            ->body( $this->notification_data['push_body'] );
//            ->action('View account', 'view_account');
```

What I'm trying to do is send a user picked URL to the push notification, so that I can respond by opening up that specific URL when a user clicks on the notification. 

Thanks again for the great job you did with this library!

**Comment by cretueusebiu** [comment]
I don't think that's possible with Push Notifications   because it doesn't allow to specify a custom URL. It will always open the base URL. 

At least this was the behavior a year ago, maybe they changed it with the latest updates. Check the Push Api.

**Comment by cretueusebiu** [comment]
Try the [onclick](https://developer.mozilla.org/en-US/docs/Web/API/Notification/onclick) event. 

You can use the the `body` method to send additional data, along with the actual body then on change the sw.js to extract the actual body and the url and using the [click event](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/public/sw.js#L47) you open a url. But it's not possible to open an url from the action button.

**Comment by iamgoodbytes** [comment]
Hi @cretueusebiu. Thanks for the response!
It looks like there's an attribute "data" that can be used specifically for sending additional data with the notification:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

_data: Arbitrary data that you want associated with the notification. This can be of any data type._

Is that something that can be supported in the library?

**Comment by cretueusebiu** [comment]
Yes it's [this one](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/public/sw.js#L83) then you can retrieve it in the [click event](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/public/sw.js#L48).

**Comment by iamgoodbytes** [comment]
I couldn't find a data property in https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushMessage.php - isn't that required there?

**Comment by cretueusebiu** [comment]
The `data` is the entire notification payload not a prop. Just `console.log(data)` in `WebPush .sendNotification` to see the contents.

**Comment by iamgoodbytes** [comment]
From what I understand in [this spec](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) is that `data` should be a prop just like icon, body and actions. That would be the only way to pass complementary data to the notification. Otherwise, we'd be misusing e.g. the body prop in order to attach extra data there right?

**Comment by cretueusebiu** [comment]
What I mean is that the `data` prop from the notification (JS) is the data from the notification object (PHP), from the [toArray method](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushMessage.php#L133).

**Comment by cretueusebiu** [comment]
Or you can use the actual actions. 

Example:

```php
->action('my_custom_action', 'http://domain.app/custom-url')
```

Then is sw.js in `sendNotification` you filter the actions and remove this one since it's not indented to be an actual action.

Then in `notificationClick` you have:

```javascript
const data = event.notification.data

console.log(data.actions) // will be an array that contains your custom action and you get the it's url from there.
```

**Comment by iamgoodbytes** [comment]
Great idea. However, when I remove the action before sending it's also not available in the `notificationClick`event, because we just removed the action ?

**Comment by cretueusebiu** [comment]
You don't remove it, just filter it out:

```javascript
// sendNotification
actions: (data.actions || []).filter(action => action.title !== 'my_custom_action')
```

**Comment by iamgoodbytes** [comment]
Sorry, I still don't get how that changes things. The `.filter()` method will return a new array containing only actions that are not titled 'my_custom_action', thus removing the actions itself from the notification before it gets sent? When I click the sent notification, the `.data.actions` are empty, because they have been filtered out? Or am I missing the point here?

**Comment by iamgoodbytes** [comment]
**UPDATE** : for anyone who's trying to do the same thing without using the .data property (which currently only works in Chrome), I've solved this by creating a global variable `var CUSTOM_ACTION_URL;` in my serviceworker and using that throughout my script. 

It's not ideal, but it does the job.

Thanks again for looking into this @cretueusebiu (reach out via Twitter @GoodBytes if you will, I'd love to show you what I've built with your package)
