### ISSUE TITLE
max execution time

### ISSUE THREAD

**Issue by iamgoodbytes** [laravel-notification-channels/webpush#27]
I'm sending lots of push messages at one (around 5.000) and I'm getting the error: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 120 seconds exceeded 
in vendor/mdanter/ecc/src/Math/GmpMath.php:34

Any idea how I can solve that?

**Comment by cretueusebiu** [comment]
Try increasing the php max execution time. 

Can you post the full stack trace ?

**Comment by iamgoodbytes** [comment]
I had the timeout at 240. Is there a specific way the timeout occurs so that I can take a deeper look as why my queue isn't handling this?

Does is have to do with encrypting the messages?

Thanks for helping out!

**Comment by cretueusebiu** [comment]
I use [this package](https://github.com/web-push-libs/web-push-php) for webpush that uses the library where the errors comes from. Might want to take a look at that first.

**Comment by iamgoodbytes** [comment]
Full stack trace with execution time set to unlimited:

`LogicException: Cannot change a rejected promise to fulfilled 
in /home/myapp/vendor/guzzlehttp/promises/src/Promise.php:130
Stack trace:
#0 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(113): GuzzleHttp\Promise\Promise->settle('fulfilled', Object(GuzzleHttp\Promise\RejectedPromise))
#1 /home/myapp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(179): GuzzleHttp\Promise\Promise->resolve(Object(GuzzleHttp\Promise\RejectedPromise))
#2 /home/myapp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(108): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
#3 /home/myapp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#4 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#5 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/myapp/vendor/guzzlehttp/promises/src/EachPromise.php(101): GuzzleHttp\Promise\Promise->wait()
#10 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\EachPromise->GuzzleHttp\Promise\{closure}(true)
#11 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#12 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#14 /home/myapp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#15 /home/myapp/vendor/minishlink/web-push/src/WebPush.php(141): GuzzleHttp\Promise\Promise->wait()
#16 /home/myapp/vendor/laravel-notification-channels/webpush/src/WebPushChannel.php(48): Minishlink\WebPush\WebPush->flush()
#17 /home/myapp/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): NotificationChannels\WebPush\WebPushChannel->send(Object(App\User), Object(App\Notifications\PushNotification))
#18 /home/myapp/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\User), '1d7e72e4-d9c3-4...', Object(App\Notifications\PushNotification), 'NotificationCha...')
#19 /home/myapp/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\PushNotification))
#20 /home/myapp/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\PushNotification))
#21 /home/myapp/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(App\User), Object(App\Notifications\PushNotification))
#22 /home/myapp/app/Jobs/SendPushCampaign.php(38): App\User->notify(Object(App\Notifications\PushNotification))
#23 [internal function]: App\Jobs\SendPushCampaign->handle()
#24 /home/myapp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /home/myapp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /home/myapp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /home/myapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /home/myapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#29 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\SendPushCampaign))
#30 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\SendPushCampaign))
#31 /home/myapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\SendPushCampaign), false)
#33 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(69): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#34 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#35 /home/myapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\SendPushCampaign))
#36 /home/myapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(159): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\SendPushCampaign))
#37 /home/myapp/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\SendPushCampaign))
#38 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(378): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\SendPushCampaign))
#39 /home/myapp/app/Campaign.php(80): dispatch(Object(App\Jobs\SendPushCampaign))
#40 /home/myapp/app/Http/Controllers/CampaignController.php(285): App\Campaign->queue()
#41 [internal function]: App\Http\Controllers\CampaignController->send(Object(Illuminate\Http\Request))
#42 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#43 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('send', Array)
#44 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\CampaignController), 'send')
#45 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#46 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#47 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/myapp/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/myapp/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/myapp/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#69 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#70 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#71 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#72 /home/myapp/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /home/myapp/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Clockwork\Support\Laravel\ClockworkMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#88 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /home/myapp/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /home/myapp/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#93 /home/myapp/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#94 {main}`

**Comment by cretueusebiu** [comment]
Not sure what might be the cause. Try sending them in chunks.

Do you just query all the users and send the notifications ?

**Comment by iamgoodbytes** [comment]
I am segmenting them like this: https://github.com/laravel-notification-channels/webpush/issues/22
That means that the function pushSubscriptions returns around 5000 push notification on one of my domains. They should receive the same push notification, it's a sort of campaign.

Does that make sense?

I tried adding this to a job `dispatch(new SendPushCampaign($user, $notification));`and in the job itself the handle() looks like this `$this->user->notify(new PushNotification($this->notification));``

What I don't get is that the ajax call that should dispatch this jobs now seems to hang until it crashes with the error above, while I would have expected it to just run quickly and then let the job queue handler do the rest in the background. That might be another issue on my end;

**Comment by cretueusebiu** [comment]
I would use the Laravel chunk method on the query and only take like 500 - 1000 users and send the notifications.

**Comment by iamgoodbytes** [comment]
I found my issue, it has to do with queues not having the same data about the campaign that the sync queue handler has. I think it has to do with me assigning $static data to the user object and the queue handler not having that data while the sync handler does have that.

**Comment by cretueusebiu** [comment]
I don't know how you have the users set up. Is this segment prop like a group id for the users ? If you can maybe explain it a bit..

**Comment by iamgoodbytes** [comment]
The push_subscriptions table has a column 'segment', 'domain_id', 'uid' and others. That way, I can overwrite the users' `public function pushSubscriptions()` and return a result depending on those properties, exactly like what we discussed here some time ago: https://github.com/laravel-notification-channels/webpush/issues/22#issuecomment-293483318

This works great when using Laravel's QUEUE_DRIVER=sync, but when I use the database driver instead, the static properties 'segment', 'domain_id', 'uid' are "lost" from the $user object:

`dispatch(new SendPushCampaign($user, $notification));`

I believe the same problem is also described here to give you some more context: https://laracasts.com/discuss/channels/laravel/using-static-variable-in-job-class

Does that make sense to you? Anyway, thanks a lot for helping out, this clearly has nothing to do with your library so the issue itself can be closed.

**Comment by cretueusebiu** [comment]
Try something like this:

```php
class SendPushCampaign implements ShouldQueue
{
    public $user;
    public $segment;
    public $notification;

    public function __construct($user, $notification, $segment)
    {
        $this->user = $user;
        $this->segment = $segment;
        $this->notification = $notification;
    }

    public function handle()
    {
        $this->user->segment = $this->segment;
 
        $this->user->notify($this->notification);
    }
}
```

Then in `User.php` you have:

```php
public $segment;

public function pushSubscriptions()
{
    if (isset($this->segment)) {
        return $this->hasMany(PushSubscription::class)->where('segment', $this->segment);
    }

    return $this->hasMany(PushSubscription::class);
}
```

Then you dispatch the job with the segment you want:
```php
dispatch(new SendPushCampaign($user, $notification, 'segment-value'));
```

**Comment by iamgoodbytes** [comment]
Thanks for your detailed input, it's really helpful to me and I appreciate it. 
Again, this works with the async queue driver, but when I try to run it through my database queue handler I'm confused as to why this Log statement does not show up in my laravel.log?

in SendPushCampaign.php:

```
public function handle()
    {
     	// add these in
        $this->user->segment = $this->segment;
        $this->user->domainId = $this->domainId;
        $this->user->targetTime = $this->targetTime;
        $this->user->uid = $this->uid;

        Log::info("HANDLE INFO: "  . $this->user->domainId );

        $this->user->notify(new PushNotification($this->notification));
    }
```

in User.php, the following log 
`Log::info('We have targeted domain ID: ' . $this->domainId);`
this does not print $this->domainId, as if it is still NULL.

In my jobs table, I can see this record showing up until it gets processed, so it looks like all the data is there. Still :

`{"displayName":"App\\Jobs\\SendPushCampaign","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":10,"timeout":null,"data":{"commandName":"App\\Jobs\\SendPushCampaign","command":"O:25:\"App\\Jobs\\SendPushCampaign\":11:{s:5:\"tries\";i:10;s:7:\"\u0000*\u0000user\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":2:{s:5:\"class\";s:8:\"App\\User\";s:2:\"id\";i:1;}s:15:\"\u0000*\u0000notification\";a:5:{s:10:\"push_title\";s:21:\"Yo, testing this out!\";s:9:\"push_body\";s:12:\"Bingo Bango!\";s:9:\"push_icon\";s:92:\"https:\/\/app.com\/storage\/uploads\/icons\/7xR38TxeRkKLCfXZ6k5GghZnnQ6qNtYkVUDkZ4Ec.png\";s:11:\"push_action\";s:22:\"https:\/\/www.google.com\";s:19:\"campaign_identifier\";s:40:\"38e4b6835bbb9490c90101997e916584fb881782\";}s:7:\"segment\";N;s:8:\"domainId\";i:1;s:10:\"targetTime\";N;s:3:\"uid\";N;s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:5:\"delay\";N;}"}}`

**Comment by iamgoodbytes** [comment]
Update: one of the stupid mistakes I made was not restarting the Laravel queue after updating my code. That way, the queue process had cached the old code and didn't work.

Right now, the job is still failing because of the large amount of push notifications it's sending. Just need to figure out a way to split the job into multiple queues.

**Comment by iamgoodbytes** [comment]
Where would you say, would be the best location in code to loop over all pushSubscriptions and dispatch them individually from there?

**Comment by iamgoodbytes** [comment]
My current guess is that the problem is that gcm only allows sending one message to 1000 subscribers unless you use "topic messaging". Have you used the or do you know if the lib supports doing so? https://firebase.google.com/docs/cloud-messaging/android/topic-messaging

**Comment by cretueusebiu** [comment]
Not sure about that. This package uses minishlink/web-push, so check if that has something like that.

**Comment by iamgoodbytes** [comment]
FCM is supported, but actually not being used when you use Web Push API. 

On a final note (seriously), I'm trying to work around my problem by sending notification in a laravel job. For that, I need to be able to access your sendNotification() method inside WebPushChannel()

Problem is that I can't find a way to complete my code below (the part that says ???). 
I can't just instantiate a new WebPushChannel() object, because the constructor require a WebPush class() which in return requires configuration parameters to instantiate. 

Is that something you could point out to me? 

??? needs to be something like 
`new WebPushChannel( new WebPush( WebPushChannel->webPushConfig() ) )` but I can't figure out how I can do so correctly.

```
$x = ???;
$x->sendNotification(
            $this->sub->endpoint,
            $this->payload,
            $this->sub->public_key,
            $this->sub->auth_token
        );
```

I realise that this issue has evolved into a support ticket now, but being so close I'd like to ask you if you know of a way to solve this. 

Thanks again for your time and effort you've put into this library and supporting it, I certainly appreciate your help!
