### ISSUE TITLE
Action Option Not working

### ISSUE THREAD

**Issue by saadrawasia** [laravel-notification-channels/webpush#33]
When Providing action like this:

return WebPushMessage::create()
            // ->id($notification->id)
            ->title('Approved!')
            ->icon('/approved-icon.png')
            ->body('Your account was approved!')
            ->action('View account', 'view_account');

action option not working. Does not show any action. 

When i click on notification. I use notificationclick event listener and console, the event. In event action array is empty. Please fix this or explain how can i do this. I want to pass url in action

**Comment by cretueusebiu** [comment]
Update to the latest version of push and if you console.log the event in `sw.js@notificationClick`  you will get:

![2p7axe1ar5kj_80s1ddesg 1](https://user-images.githubusercontent.com/1517945/32858969-da7f6fb4-ca55-11e7-8629-f016bfd2d4de.png)

As you can see the action is in the event now.
