### ISSUE TITLE
artisan migrate don't work

### ISSUE THREAD

**Issue by dfuentes141** [laravel-notification-channels/webpush#36]
Show this:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `push_subscriptions` add unique `push_subscriptions_endpo
  int_unique`(`endpoint`))

**Comment by cretueusebiu** [comment]
Try this https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by dfuentes141** [comment]
Thanks, its work
