### ISSUE TITLE
[Question] How to pass url to a web push action?

### ISSUE THREAD

**Issue by neorganic** [laravel-notification-channels/webpush#37]
Can you give an example on how to pass an url to a web push action? The one in the demo just redirects to the root of the site. Thanks in advance !

**Comment by cretueusebiu** [comment]
Use the data method to set arbitrary data:

```php
(new WebPushMessage)
    ->data(['url' => ''])
```

**Comment by neorganic** [comment]
I get an error when I use(uncomment) data method:

 [2017-12-05 14:32:41] production.ERROR: Call to undefined method NotificationChannels\WebPush\WebPushMessage::data()

```
    public function toWebPush($notfiable, $notification){
        return (new WebPushMessage)
           // ->id($notification->id)
            ->title('Ready!')
            ->icon('/notification-icon.png')
            ->body('Your up time report is ready!')
            ->action('View report', 'view_report');
         //  ->data(['url' => route('down-report')]);
    }
```

**Comment by cretueusebiu** [comment]
Make sure to use the [latest version](https://github.com/laravel-notification-channels/webpush/releases).

**Comment by neorganic** [comment]
Silly me to missed that... Thanks!! Resolved !
