### ISSUE TITLE
[Question] Do pushes have to be tied to a 'user' model?

### ISSUE THREAD

**Issue by adamkelso-rg** [laravel-notification-channels/webpush#38]
First off, thanks so much for this package and the others for each provided channel. You all rock.

Is there any way to use this package without strongly tying push notifications to the `users` table. I'm currently working on an app where people can subscribe to web push notifications without creating an account. They're saved in a completely different entity, "Contacts", and are not saved in the `users` table.

The problem lies in that it looks like everything in this package is strongly tied to a `User` model and has a hard coded 'users' table in the migration and a `user_id` on the PushSubscription model.

If not, I guess I can implement this using the webpush library directly, but wanted to ask first. Thanks again.

**Comment by cretueusebiu** [comment]
It should work on other notifiable entities too. 
After you publish, edit the `create_push_subscriptions_table` migration and change the `user_id` according to your case, then add the `HasPushSubscriptions` trait to your  entity and make sure to override any methods from that trait that use the `user_id` (`pushSubscriptionBelongsToUser`).
