### ISSUE TITLE
notifications not sent to mobile web browsers

### ISSUE THREAD

**Issue by adnanmokhtar** [laravel-notification-channels/webpush#43]
notifications sent to desktop web browsers but not sent to mobile web browsers

how to send notifications to mobile web browsers?

**Comment by cretueusebiu** [comment]
It should work on mobile too. See my [demo](https://github.com/cretueusebiu/laravel-web-push-demo).

**Comment by adnanmokhtar** [comment]
it is send to safari?

**Comment by cretueusebiu** [comment]
It's not available on Safari. 
https://developer.mozilla.org/en-US/docs/Web/API/PushManager
