### ISSUE TITLE
customer user tables and primary id

### ISSUE THREAD

**Issue by hybrid1969** [laravel-notification-channels/webpush#46]
i am using a customer table with UUID instead of interger id's and I am getting -

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'customer_users_id' in 'field list'

Can i make changes outside the provider files so as not to break the code.

**Comment by cretueusebiu** [comment]
I think if you change the migration and rework HasPushSubscriptions to use the uuid you should be good.

**Comment by hybrid1969** [comment]
i was hoping i wouldn't have to customize the published code too much but thanks

**Comment by cretueusebiu** [comment]
You don't customize the code, you just override the methods that need to be changed in your model.

**Comment by hybrid1969** [comment]
ah ok, sorry for my ignorance but ive never done that before. 

Hints on best way to do that :)

**Comment by cretueusebiu** [comment]
You should first change the `push_subscriptions` migration to use a string or uuid data type of the `user_id` then in your user model copy the `pushSubscriptionBelongsToUser` method from [HasPushSubscriptions.php](https://github.com/laravel-notification-channels/webpush/blob/master/src/HasPushSubscriptions.php) and change it like this:

```php
public function pushSubscriptionBelongsToUser($subscription)
{
    return $subscription->user_id === $this->getAuthIdentifier();
}
```

I think that's all.

**Comment by hybrid1969** [comment]
ok it was the were to put the overidde that was confusing me, TY will try this
