### ISSUE TITLE
app.js:33556 WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753' failed: Invalid frame header

### ISSUE THREAD

**Issue by qodeanil** [laravel-notification-channels/webpush#47]
I have installed your Laravel package for pusher in my application. however, i am getting the issue as

**_app.js:33556 WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753?protocol=7&client=js&version=4.2.2&flash=false' failed: Invalid frame header_**

_**WebSocket connection to 'ws://ws.pusherapp.com/app/67006e7ceebb6ff4d753?protocol=7&client=js&version=4.2.2&flash=false' failed:**_ 

**_WebSocket is closed before the connection is established._**

**Whereas "Enable Push Notification" Button is always disabled.** Please let me know how I can solve this issue.

**Comment by qodeanil** [comment]
Here is the screen shots attached

![screen shot 2018-03-15 at 8 10 24 pm](https://user-images.githubusercontent.com/16719253/37470636-051f7be0-2890-11e8-9cdb-11ac177f9566.png)
![screen shot 2018-03-15 at 8 10 09 pm](https://user-images.githubusercontent.com/16719253/37470639-05622c60-2890-11e8-829b-8e52562e5e8d.png)

**Comment by cretueusebiu** [comment]
This is related to the actual demo, please open an issue [there](https://github.com/cretueusebiu/laravel-web-push-demo).
