### ISSUE TITLE
New Feature request: Add Edge support

### ISSUE THREAD

**Issue by jvjvjv** [laravel-notification-channels/webpush#48]
Firefox and Edge are both at the bottom of the market share, but at least Firefox has support. Understanding that Edge is, well, Edge, do you have plans to add that feature to this package?

**Comment by cretueusebiu** [comment]
It already works on Edge, however you need to manually enable service workers in Edge 16. In version 17 it will be enabled by default. 

See the [ServiceWorkerRegistration](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration#Browser_compatibility) compatibility table.
 
![screenshot_1](https://user-images.githubusercontent.com/1517945/38387892-292c1154-3922-11e8-8cc6-2bbde0a28c2f.png)

**Comment by jvjvjv** [comment]
Perhaps, then, the documentation should be updated.
