### ISSUE TITLE
`toWebPush` function of Notification is not called

### ISSUE THREAD

**Issue by sorribes22** [laravel-notification-channels/webpush#50]
Hi, I can dispatch events using pusher as broadcaster. But when I try to notify user using WebPush, the `toWebPush` function of **Notification** is not called. If I log some information on this function is not written on the log and, of course, pusher debugger console does not show the message.

Notification class code
```
public function via($notifiable)
    {
        return [
//            'mail',
//            'nexmo',
            WebPushChannel::class
        ];
    }

public function toWebPush($notifiable, $notification)
    {
        Log::info('hola');
        Log::info($notifiable);
        Log::info($notification);
        return (new WebPushMessage)
            ->title('Approved!')
            ->body('Your account was approved!');
    }
```

* **Do you know why is not called?**
* **Did I miss some step?**

Thanks

**Comment by cretueusebiu** [comment]
Make sure the users you're trying to send the push notifications have registered push subscriptions.
Use `$user->pushSubscriptions` to see what subscriptions a user has.
