### ISSUE TITLE
Add notification to guest 

### ISSUE THREAD

**Issue by ahmedalmulki** [laravel-notification-channels/webpush#51]
Thanks for this nice library , I already download the demo and try it , but actually I am working with project need to let visitors enable notification without register or do anything else , how can I do that with this library ?

**Comment by cretueusebiu** [comment]
You'll need a model for the guest users `GuestUser` that you use to identify users based on their browser/ip and add the `HasPushSubscriptions` trait to that.
Then you need to modify the `push_subscriptions` migration to use the foreign key of the guest_users table.
And also override the `pushSubscriptionBelongsToUser` method on the `GuestUser` model to return whether the subscription belongs to that user or not.

**Comment by ahmedalmulki** [comment]
OK I got this thanks,then what can I do if I want to send notifications to all guests ?

**Comment by cretueusebiu** [comment]
See https://laravel.com/docs/5.6/notifications#sending-notifications

**Comment by ahmedalmulki** [comment]
thanks I can know send notifications , but I want to delete subscriber from push_subscriptions table when user chose block from browser tab 
![block](https://user-images.githubusercontent.com/11661064/40619457-c043a6c0-629d-11e8-9a61-ce599976cfc6.png)
Thanks in advance ..

**Comment by bonucci** [comment]
> You'll need a model for the guest users `GuestUser` that you use to identify users based on their browser/ip and add the `HasPushSubscriptions` trait to that.
> 
> Then you need to modify the `push_subscriptions` migration to use the foreign key of the guest_users table.
> 
> And also override the `pushSubscriptionBelongsToUser` method on the `GuestUser` model to return whether the subscription belongs to that user or not.

This solution isnt the best

> You'll need a model for the guest users `GuestUser` that you use to identify users based on their browser/ip and add the `HasPushSubscriptions` trait to that.
> 
> Then you need to modify the `push_subscriptions` migration to use the foreign key of the guest_users table.
> 
> And also override the `pushSubscriptionBelongsToUser` method on the `GuestUser` model to return whether the subscription belongs to that user or not.

But if you going based on ip/browser you can have more than one computer sharing same ip on a network.
