### ISSUE TITLE
For multi-tenant application

### ISSUE THREAD

**Issue by little-isaac** [laravel-notification-channels/webpush#56]
I am trying your webpush package for my one of application. 
My application has Multi-tenant schema's as diff.  database.

The issue is there is no option to pass database connection for PushSubscription model.
How can i do that?

**Comment by cretueusebiu** [comment]
In your model override the `pushSubscriptions` method and return a relation with your `PushSubscription` where you set a custom connection and extend the base `PushSubscription`.

**Comment by Broutard** [comment]
And `updatePushSubscription()` which use 
```
$subscription = PushSubscription::findByEndpoint($endpoint);
```

:(

**Comment by vesper8** [comment]
I just added PR https://github.com/laravel-notification-channels/webpush/pull/85 which lets you specify the database table and connection as a configuration parameter

**Comment by lmatab** [comment]
Thanks a lot for this pr @vesper8 

I am using a package to make my app multitenancy, so in order to save the webpush notification information in the right tenants DB you just need to   change the  database_connection to null in the  webpush.php file

```     'database_connection' => env('WEBPUSH_DB_CONNECTION', null),
```
