### ISSUE TITLE
Problem with notification content

### ISSUE THREAD

**Issue by AlexandreVaudelin** [laravel-notification-channels/webpush#57]
Hi, I'm having a problem with notifications.

Be aware that I'm using Lumen, not Laravel. I installed and configured anything I needed to make this library working with Lumen (at least I think so)

What works:
- Subscriptions are correctly saved in the Database.
- When I do $user->pushSubscriptions on a test user, it shows me the correct data.
- Notifications are SENT, i receive them on chrome desktop or chrome android.

Problem : BUT, I have no content in the notifications. The only infos I have in the notifications are:
- app url
- "This site has been updated in the background" message

It looks like to me that no content is added on the payload, and maybe that's why chrome just display a default message

NotificationController.php send() function (my entry point in the router to send my test notifications):

```
public function send()
    {
        $user = User::find('2');
        $user->notify(new PushNotification);
        return response()->json('test', 201);
    }
```

PushNotification class (some parts of it):

    public static function via($notifiable)
    {
        return [WebPushChannel::class];
    }

    /**
     * Get the array representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'title' => 'Hello from Laravel!',
            'body' => 'Thank you for using our application.',
            'action_url' => 'https://laravel.com',
            'created' => Carbon::now()->toIso8601String()
        ];
    }

    /**
     * Get the web push representation of the notification.
     *
     * @param  mixed  $notifiable
     * @param  mixed  $notification
     * @return \Illuminate\Notifications\Messages\DatabaseMessage
     */
    public function toWebPush($notifiable, $notification)
    {
        return (new WebPushMessage)
            ->title('Approved!')
            ->icon('/approved-icon.png')
            ->body('Your account was approved!')
            ->action('View account', 'view_account');
        // ->data(['id' => $notification->id])
        // ->badge()
        // ->dir()
        // ->image()
        // ->lang()
        // ->renotify()
        // ->requireInteraction()
        // ->tag()
        // ->vibrate()
    }

As you can see, I tried to do exactly like in the [example](https://github.com/cretueusebiu/laravel-web-push-demo).

I have been spending hours trying to make it work, with no success. Any help would be greatly appreciated.

**Comment by cretueusebiu** [comment]
Make sure the [service provider](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushServiceProvider.php) works with Lumen. 
Check if `new WebPush($this->webPushConfig());` is created with the correct configuration.

**Comment by AlexandreVaudelin** [comment]
Thanks for your answer.

In app.php (where we register srvice providers in lumen), there is that line I added a while ago : 
`$app->register(NotificationChannels\WebPush\WebPushServiceProvider::class);`

I see the `new WebPush($this->webPushConfig());` in the provider, but I'm not sure how and where to test/check its configuration

**Comment by cretueusebiu** [comment]
Try with a simple `dd($this->webPushConfig())`.

**Comment by AlexandreVaudelin** [comment]
Ok, I did that directly in the provider, I have this in return 
`array(1) { ["VAPID"]=> array(3) { ["publicKey"]=> string(87) "BKtjsqxxxxxxxxxxxxxxx" ["privateKey"]=> string(43) "SbNgxxxxxxxxxxxx" ["subject"]=> string(8) "http://:" } }`

(the keys are ok, just hide them)

**Comment by AlexandreVaudelin** [comment]
Ok, so I debugged hard in your library code and web-push-php code to see if the payload was generated correctly and apparently, YES.
Now I will check on the front side if I receive and display things correctly.

As it seems it is not connected to your library, I will close the issue in the afternoon. Thanks again for your help.

**Comment by carlos-cruz** [comment]
> Ok, so I debugged hard in your library code and web-push-php code to see if the payload was generated correctly and apparently, YES.
> Now I will check on the front side if I receive and display things correctly.
> 
> As it seems it is not connected to your library, I will close the issue in the afternoon. Thanks again for your help.

Did you succeed with this @AlexandreVaudelin ? Im having the same issue..

**Comment by mahdisoftdev** [comment]
hellow i have same prob in laravel,what should i have done?
