### ISSUE TITLE
how to integrate with existing service worker in vue-cli PWA

### ISSUE THREAD

**Issue by vesper8** [laravel-notification-channels/webpush#58]
I'm using vue-cli RC5 with the SPA/PWA template so I already have a service worker which is generated and managed entirely by the vue-cli default build process

in your tutorial it seems you create a service worker of your own, I am wondering if I can have two service workers or if I have to attach to the one created by vue-cli by modifying the default generated file

also.. if I understand correctly.. using Laravel as the "pusher" is an alternative to using something like OneSignal right?

**Comment by cretueusebiu** [comment]
You can import other scripts with [importScripts](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#importScripts)

So you don't have to register the service worker like in my demo app, just import a script that listens for push notifications.

OneSignal is a dedicated service for push notifications, with this implementation you don't rely on third party services (except the browser's own service for notifications).
