### ISSUE TITLE
Pushing to single endpoints

### ISSUE THREAD

**Issue by stephenbennett-uk** [laravel-notification-channels/webpush#61]
Is it possible to push a notification out to a single endpoint, rather than all endpoints belonging to a user?

For example, the user might have requested notifications be sent to their desktop and mobile but only wants certain notifications sent to their mobile. Or maybe sending out a test notification upon registering a device - you'd only want those on the device just registered.

**Comment by cretueusebiu** [comment]
The `routeNotificationForWebPush` method returns all the subscriptions for a user. And there's no way to pass like a parameter to filter them. You'll have to write a custom implementation for [WebPushChannel](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushChannel.php).

Or I think you can create a fake notifiable with a `pushSubscriptions` property that contains only the subscriptions you want the notification to be sent to.
