### ISSUE TITLE
Safari bug undefined is not an object (evaluating 'navigator.serviceWorker.getRegistration')

### ISSUE THREAD

**Issue by odhikari** [laravel-notification-channels/webpush#62]
Do we have any updates regarding this issue?
I am not able to subscribe in Safari browser.

Thanks in advance,

**Comment by cretueusebiu** [comment]
Safari does not support the standard [Push Api](https://caniuse.com/#feat=push-api). 
But it should not throw an error though.

**Comment by odhikari** [comment]
Thank you for your quick response. Do we have any alternative option for
safari ?
