### ISSUE TITLE
URL in action is not woking ?

### ISSUE THREAD

**Issue by odhikari** [laravel-notification-channels/webpush#63]
URL defined in action is not working for me. Here is my code.

public function toWebPush($notifiable, $notification)
    {
        return (new WebPushMessage)
        ->title('Title section is here!')
        ->icon('/images/logo.png')
        ->body('Here is my body section.' )
        ->action('View app', 'http://127.0.0.1:8000/dashboard/');
    }

I am getting push notification but once I click on the popup it redirects to the base URL. In above, it redirects to the base URL (i.e. http://127.0.0.1:8000) where I wanted to redirect to the dashboard page.

Help me out from this issue.
Thanks in advance.

**Comment by cretueusebiu** [comment]
The `action` method accepts title and action, but the action is not an url. If you look at my [sw.js](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/public/sw.js) you'll see:

```javascript
notificationClick (event) {
  if (event.action === 'some_action') {
    // Do something...
  } else {
    self.clients.openWindow('/')
  }
}
```

That's where you'd have to implement your logic to open links or whatever. In this case it just opens the base url.

**Comment by odhikari** [comment]
I tried  the above one

notificationClick (event) {
      // console.log(event.notification)

      if (event.action === 'view_app') {
        window.location = "https://www.github.com"
      } else {
        self.clients.openWindow('/')
      }
    },


where 'view_app' is define in action.

But this is not working. Could you please help me out.

Thanks

**Comment by cretueusebiu** [comment]
You'll have to use `self.clients.openWindow`.

https://developer.mozilla.org/en-US/docs/Web/API/Clients/openWindow

**Comment by zgordan-vv** [comment]
This is working but is it possible to do AJAX requests to laravel API from service workers? I use:

self.addEventListener('notificationclick', function(event) {
        event.notification.close();
        fetch('notifications/handle-action/', {
                method: "post",
                body: event.action,
                credentials: 'same-origin',
        }).then(function(response) {
                console.log(response);
        });
});

but looks like POST request is going unauthenticated and then rejected. Thank you

**Comment by odhikari** [comment]
Thanks @Cretu

It's working now.

**Comment by bilogic** [comment]
> The `action` method accepts title and action, but the action is not an url. If you look at my [sw.js](https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/public/sw.js) you'll see:
> 
> ```js
> notificationClick (event) {
>   if (event.action === 'some_action') {
>     // Do something...
>   } else {
>     self.clients.openWindow('/')
>   }
> }
> ```
> 
> That's where you'd have to implement your logic to open links or whatever. In this case it just opens the base url.

On Android 10 , the notification has to be further expanded to reveal the actions.
If I tap on the notification without expanding, `event.action` is an empty string.

What I would like to do is to be able to assign different `action` values for different messages.

Is there a way to set a value from the `WebPushMessage`?
