### ISSUE TITLE
Is it possible to send notifications only on mobile and not on desktop? 

### ISSUE THREAD

**Issue by milanchheda** [laravel-notification-channels/webpush#64]
Can we send notifications to users only on mobile devices and not on desktop?

Also, notifications are currently sent on both mobile and desktop. So after dismissing a notification on mobile, I still see them on desktop, why so? I am talking about webpush notifications and not database notifications.

**Comment by cretueusebiu** [comment]
That's beyond the scope of this package. You'll need a few more things to make it work that way. 

Check out [this demo](https://github.com/cretueusebiu/laravel-web-push-demo), it uses Pusher to dismiss the notification from the other devices.
