### ISSUE TITLE
Not really compatible with MySQL 5.6

### ISSUE THREAD

**Issue by YavorK** [laravel-notification-channels/webpush#67]
Hello, 

Your package works quite nicely on my local machine...

I do understand this is not a bug and probably using a newer MySQL version or PostgreSQL would fix things automatically. Because it works fine on latest MariaDB on my PC

I have been using your package in my project. However my host only supports MySQL 5.6 which does not support such long columns to index. 

file: `webpush/migrations/create_push_subscriptions_table.php.stub`
code: ` $table->string('endpoint', 500)->unique();`

Probably using another column of `endpoint` hashes (say sha1s of `endpoint` value) would be faster to search (I'm thinking of shorter strings to index, not whole URLs) and also widely compatible with databases.

(I wonder also - what DB/version have you been using when developing this package? Just curious.)

**Comment by cretueusebiu** [comment]
After you published the migration, change the endpoint column to text and then migrate.

**Comment by YavorK** [comment]
Sloppy solution.

**Comment by YavorK** [comment]
"
Note that technically this is not a solution, because two different text
values may generate the same hash - ie a [hash collision](
en.wikipedia.org/wiki/Collision_(computer_science). To be *sure* of keeping
the values unique you would have to store the whole string too and *not* have
a unique index on the hash column. – Bohemian♦
<https://stackoverflow.com/users/256196/bohemian>Dec 26 '12 at 18:28
<https://stackoverflow.com/questions/14033378/make-text-column-as-unique-key#comment19404455_14033466>

"

here:
https://stackoverflow.com/questions/14033378/make-text-column-as-unique-key

**Comment by cretueusebiu** [comment]
I forgot that the column is unique. Guess 5.7 is required then.
