### ISSUE TITLE
Not receiving Web Push Notification

### ISSUE THREAD

**Issue by JuanDeLeon** [laravel-notification-channels/webpush#68]
I'm trying to test the push notifications. I have the registration process setup successfully, and print the subscription in the console, so I can hardcode the endpoint and call updatePushSubscription (see code below). The data is being stored in the DB table correctly.

Then I call the notify method. I put a Log in PushNotificaction.toWebPush() method, and it's being printed. However, I'm not receiving any notification at all on Chrome desktop when this happens. Any ideas where else I should be looking at?

```
$key = null;
$token = null;
$endpoint = 'https://fcm.googleapis.com/fcm/send/e0U-D7nEC4I:APA91bEi8Lfrh81XjxXr6Nc8LH4eJwzplaLvkjy8EYfKS-PUNHaUqnCUhlunAtjCUbrEPjLpy15TDc08m1a2J-EIDmJEyK6kdPeGSWCWaRcsxtwfmUwPHU9grqIOOBExygPt839LCf09';

Auth::User()->updatePushSubscription($endpoint, $key, $token);
Auth::User()->notify(new PushNotification);
```

**Comment by captainkirkoff** [comment]
Hi,
how did you manage to solve? I'm also in trouble not receiving any notification at all.
Thank you.

**Comment by JuanDeLeon** [comment]
Hey, I ended up using the Minishlink/web-push package directly, and then built my own classes (Message, Channel, etc) based on this package's structure.
