### ISSUE TITLE
use different TTL

### ISSUE THREAD

**Issue by StApostol** [laravel-notification-channels/webpush#70]
I need to set a lifetime for notifications.
The https://github.com/web-push-libs/web-push-php repository uses the options when calling the SendNotification method containing the TTL

**Comment by jornetsimon** [comment]
Yes, it would be good to be able to define more properties from config/webpush to webPushConfig()

**Comment by alberto-bottarini** [comment]
Take a look at this PR: https://github.com/laravel-notification-channels/webpush/pull/87
