### ISSUE TITLE
Don't work on Laravel 5.6

### ISSUE THREAD

**Issue by piep14** [laravel-notification-channels/webpush#71]
Hello,

I tried to install on Laravel 5.6, and I have this message 

> Problem 1
    - Conclusion: don't install laravel-notification-channels/webpush 3.0.1
    - Conclusion: remove minishlink/web-push v5.1.0
    - Installation request for laravel-notification-channels/webpush ^3.0 -> satisfiable by laravel-notification-channels/webpush[3.0.0, 3.0.1].
    - Conclusion: don't install minishlink/web-push v5.1.0
    - laravel-notification-channels/webpush 3.0.0 requires minishlink/web-push ^2.0 -> satisfiable by minishlink/web-push[v2.0.0, v2.0.1].
    - Can only install one of: minishlink/web-push[v2.0.0, v5.1.0].
    - Can only install one of: minishlink/web-push[v2.0.1, v5.1.0].
    - Installation request for minishlink/web-push (locked at v5.1.0) -> satisfiable by minishlink/web-push[v5.1.0].

Thank you for help.

**Comment by StApostol** [comment]
Please check composer.json or composer.lock on version minishlink/web-push. If you used not version 2.X, then you must resolve this conflict
