### ISSUE TITLE
Chrome displays "Site updated in background" unless payload is wrapped in a "notification" property

### ISSUE THREAD

**Issue by Mattnmoore** [laravel-notification-channels/webpush#73]
I was having issues where my notifications wouldn't display if my site was in the background. It would just display "This site has updated in the background."

I made the following changes to `WebPushChannel.php` and it started working as expected:

Lines 37-38
```
$payload = ['notification' => $notification->toWebPush($notifiable, $notification)->toArray()];
$payload = json_encode($payload);
```

**Comment by Mattnmoore** [comment]
I can also make a PR if you prefer.

**Comment by cretueusebiu** [comment]
Is this documented somewhere ? Does it affect the sw.js file from the demo in any way?

**Comment by Mattnmoore** [comment]
I'm not sure if it affects the demo. It is documented in the Google docs located here:
https://developers.google.com/web/fundamentals/push-notifications/sending-messages-with-web-push-libraries.

I tested with Angular Service Workers and did not have to change anything, and it works on Chrome and Firefox.

**Comment by ngoahamos** [comment]
having same issue. @Mattnmoore any workaround?

**Comment by Mattnmoore** [comment]
@ngoahamos I just forked the package and made the change myself as outlined in the original post. @cretueusebiu were you able to look at this at all?

**Comment by Mattnmoore** [comment]
I'm currently using my fork until my PR gets accepted as this package does not work without it. PR fixes issue and has been tested with Chrome and Firefox.

**Comment by cretueusebiu** [comment]
I can't find anywhere about wrapping the payload with a `notification`. 
If you still want to wrap it, define a custom `WebPushMessage` that extends the default WebPushMessage and just override the [toArray](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushMessage.php#L278) method.


```php
public function toArray()
{
    return ['notification' => Arr::except(array_filter(get_object_vars($this)), ['options'])];
}
```

**Comment by marydelapedra** [comment]
@cretueusebiu Thank you for the suggestion. Works fine using a custom class extending the WebPushMessage.
