### ISSUE TITLE
Support for multiple models (Polymorphic Relations)

### ISSUE THREAD

**Issue by dror3go** [laravel-notification-channels/webpush#76]
Hi,

Thanks for the great package! works like a charm :smiley: 
In my use case I have several different models which need to be notified via push notifications. Currently the package's migration is using a `user_id` column, and therefore is problematic for such use cases.
Would you consider adding an option to create a migration which supports polymorphic relations (`morphs('user')` or something like that)?
Else, is there a workaround you can suggest, like passing the model's name when calling `updatePushSubscription()`?

Thanks a lot

**Comment by oele-code** [comment]
You could try my fork https://github.com/oele-code/laravel-webpush
