### ISSUE TITLE
Migrating error: "key was too long; max key length is 767 bytes" after modifying AppServiceProvider

### ISSUE THREAD

**Issue by Baspa** [laravel-notification-channels/webpush#77]
After installing the laravel-notifications-channels/webpush package I wanted to migrate the table:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePushSubscriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('push_subscriptions', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned()->index();
            $table->string('endpoint', 500)->unique();
            $table->string('public_key')->nullable();
            $table->string('auth_token')->nullable();
            $table->timestamps();

            $table->foreign('user_id')
                    ->references('id')
                    ->on('users')
                    ->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('push_subscriptions');
    }
}
```
But when I want to migrate I get the following error:

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `push_subscriptions` add unique `push_subscriptions_endpoint_unique`(`endpoint`))`

But I already modified the AppServiceProvider earlier to this:

```
public function boot()
{
    Schema::defaultStringLength(191);
}
```
So it seems to me that it shouldn't give me an error anymore because I already changed the AppServiceProvider. I also changed:

           'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',

to utf8 only but it still gives the same error.

**Comment by desthercz** [comment]
You need atleast Mysql 5.7.7 or MariaDB 10.2.2. If you have a lower version, it will throw you that error. You can bypass it by by changing `$table->string('endpoint', 500)->unique();` to `$table->string('endpoint', 500);` but there might be some errors or weird behaviour in the package if you do that. In my opinion the reason, why that column is unique, is because possible hash collision, but i might be wrong.
