### ISSUE TITLE
Composer requirements pulls in abandoned package spomky-labs/jose

### ISSUE THREAD

**Issue by carbontwelve** [laravel-notification-channels/webpush#78]
Version `^2.0` of the package `minishlink/web-push` that this package depends upon itself depends upon version `^7.0` `spomky-labs/jose` which as of now is an "abandoned" package.

This means that when doing a composer install on a project that depends on `laravel-notification-channels/webpush` composer raises the following notification:

> Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.

The package `spomky-labs/jose` while marked as abandoned will have security support up until the end of 2020 so there is some time to update `laravel-notification-channels/webpush` to use an alternative.

I don't know the details, having not delved too deep into the code but it may simply be a case of updating the `minishlink/web-push` requirement to the latest version and fixing any api changes that arise.

**Comment by Nuranto** [comment]
Note that version 3 of minishlink/web-push has not this requirement anymore.

**Comment by vesper8** [comment]
if this https://github.com/laravel-notification-channels/webpush/pull/84 could be merged then we can solve this too
