### ISSUE TITLE
this works fine the way it is!

### ISSUE THREAD

**Issue by vesper8** [laravel-notification-channels/webpush#80]
I just wasted so many hours setting this up because I read the PRs and some of the issues and went by the assumption that this package no longer worked and needed to have the dependencies updated and other things changed such as wrapping the response in a notification array as one of the PR suggests. about 6 hours of messing around trying to debug it and confused as to why it didn't work, I took a step back, installed the demo, realized the demo works fine, then stopped using my fork, or other people's forks, and used the package as-is and low and behold.. it works fine!! /facepalm Don't do like I did...

I'm using it with Laravel 5.8 by the way, and followed the tutorial from Part 2 and Part 3 of https://github.com/pimhooghiemstra/plintpwa-vue-1 which taught me a few new things about service workers

That being said.. I suppose it would be nice if the minishlink/web-push dependency could be updated.. it's still depending on v2 and v5 is out now and as I understand it one of the main benefits is that it's much more performant

**Comment by vesper8** [comment]
added a PR that upgrades minishlink/web-push to v5 https://github.com/laravel-notification-channels/webpush/pull/81

**Comment by Jannnnnn** [comment]
Unfortunately not quite correct, if the client uses angular's ngsw as a service worker then the notification must be embedded in an notification object.

https://github.com/angular/angular/blob/6200732e2360690532686c131add006cd29f3b61/packages/service-worker/worker/src/driver.ts#L313
