### ISSUE TITLE
Don't work on Laravel 4.2

### ISSUE THREAD

**Issue by edosurya** [laravel-notification-channels/webpush#88]
Hello,

I tried to install on Laravel 4.2, and this is my composer.json

"guzzlehttp/guzzle": "^6.2",
"mdanter/ecc": "dev-master as 0.5.0",
"minishlink/web-push": "^2.0"

my envi
laravel 4.2
php 7.0

Thank you for help.

**Comment by cretueusebiu** [comment]
You need at least Laravel 5.3.
