### ISSUE TITLE
Trait 'NotificationChannels\WebPush\HasPushSubscriptions' not found

### ISSUE THREAD

**Issue by muhammedfayazp** [laravel-notification-channels/webpush#89]
```
use NotificationChannels\WebPush\HasPushSubscriptions;

class User extends BaseUser
{
    use HasPushSubscriptions;
}
```

**Comment by vesper8** [comment]
```
use NotificationChannels\WebPush\HasPushSubscriptions;

class MyClass {

use HasPushSubscriptions;
```

If this isn't working then it must be because the package did not install correctly via composer. Or maybe because you need to run `composer dump`

**Comment by muhammedfayazp** [comment]
@vesper8 not working. still same error

**Comment by ShetlandJ** [comment]
Had this issue today. Followed the instructions exactly. Using Lara 6. no luck unfortunately

**Comment by JrogeT** [comment]
![image](https://user-images.githubusercontent.com/48605375/89598766-a1ebcd00-d82b-11ea-91a4-87d234220041.png)

I did this and no problem
