### ISSUE TITLE
Packagist auto-update

### ISSUE THREAD

**Issue by cretueusebiu** [laravel-notification-channels/webpush#93]
Hey @themsaid , I just released a new version of this package but it didn't show up on [packagist.org](https://packagist.org/packages/laravel-notification-channels/webpush).

Can you check on your profile on packagist.org and see if the GitHub Hook is configured ? 

Until this is resolved you can require the master branch like here:
https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/composer.json

**Comment by lukadriel7** [comment]
Hello, still no news about this issue ?

**Comment by alberto-bottarini** [comment]
+1

**Comment by rickdroce** [comment]
+1

**Comment by vesper8** [comment]
still can't install 4.0, it's not on https://packagist.org/packages/laravel-notification-channels/webpush

@themsaid this is in your ball court I think?

**Comment by Genora51** [comment]
Any news yet?

**Comment by lukadriel7** [comment]
Looks like the problem as been fixed.
