### ISSUE TITLE
Warning about spomky-labs/jose.

### ISSUE THREAD

**Issue by JexPY** [laravel-notification-channels/webpush#94]
Package spomky-labs/jose is abandoned, you should avoid using it. Use web-token/jwt-framework instead.

**Comment by vesper8** [comment]
this should be resolved if you pull in the latest 4.0 ? But there's currently an issue with being able to pull in the latest package at all

**Comment by cretueusebiu** [comment]
Unfortunately I don't have access to publish the release on packagist. 

Until then you can just require the master branch like I did:
https://github.com/cretueusebiu/laravel-web-push-demo/blob/master/composer.json

**Comment by JexPY** [comment]
Thank you I will try to ✌️
